ENT_ENTIDADEADMINISTRATIVA.ENTID_ENTIDADEADM

01 - GERAR TABELA DE ATOS NORMATIVO
02 - GERAR EXCELL DA SITUAÇÃO ATUAL DA ESTRUTURA ORGANIZACIONAL DOS ATIVOS (TRAZENDO ID COM A CONSULTA DAS SUBORDINAÇÕES DAS UNIDADES E CONSULTA VINCULACAO DE ÓRGAO  - caso existam)
03 - GERAR EXCELL COM OS DADOS PARA CARGA NO HISTÓRICO

OBS: Criar novas colunas para o histórico no Oracle para ficar igual ao estrutirta_organizacional do oracle

/* ///////////////// EXCELL ATO NORMATIVO /////////////////////////////// */




OBS: VER QUESTÃO DA VINCULACAO POIS TA VINDO UNIDADE VINCULADA A ÓRGÃO
ver onde ta os orgaos colegiados
perguntar a monique o historico da CMG onde pega


/* /////////////////////////// HISTÓRICO ATO NORMATIVO POR ENTID_ENTIDADEADM ///////////////////////// */

/* consulta nova para migração excell */


SELECT 
	
	distinct 	
	ENT.ENTID_ENTIDADEADM as ID_EST_ORGANIZACIONAL,
	ATO.ENTNM_SIGLA as SIGLA,
	ATO.ENTNM_ENTIDADEADM as DESCRICAO,
	TALNM_TIPOALTERACAO as desc_acao_antigo_sigeo,
	[ID_TIPO_ACAO_ATO_NORMATIVO] =
	CASE
	WHEN (SELECT TALID_TIPOALTERACAO FROM ATO_ATONORMATIVO WHERE ATOID_ATONORMATIVO =  MAX(ATO.ATOID_ATONORMATIVO) ) = '1' THEN '1' -- CRIACAO
	WHEN (SELECT TALID_TIPOALTERACAO FROM ATO_ATONORMATIVO WHERE ATOID_ATONORMATIVO =  MAX(ATO.ATOID_ATONORMATIVO) ) = '2' THEN '7' -- EXTINCAO
	WHEN (SELECT TALID_TIPOALTERACAO FROM ATO_ATONORMATIVO WHERE ATOID_ATONORMATIVO =  MAX(ATO.ATOID_ATONORMATIVO) ) = '3' THEN '2' -- ALTERACAO
	WHEN (SELECT TALID_TIPOALTERACAO FROM ATO_ATONORMATIVO WHERE ATOID_ATONORMATIVO =  MAX(ATO.ATOID_ATONORMATIVO) ) = '4' THEN '2' -- ALTERACAO
	WHEN (SELECT TALID_TIPOALTERACAO FROM ATO_ATONORMATIVO WHERE ATOID_ATONORMATIVO =  MAX(ATO.ATOID_ATONORMATIVO) ) = '6' THEN '7' -- EXTINCAO
	WHEN (SELECT TALID_TIPOALTERACAO FROM ATO_ATONORMATIVO WHERE ATOID_ATONORMATIVO =  MAX(ATO.ATOID_ATONORMATIVO) ) = '7' THEN '5' -- TRANSFORMACAO
	WHEN (SELECT TALID_TIPOALTERACAO FROM ATO_ATONORMATIVO WHERE ATOID_ATONORMATIVO =  MAX(ATO.ATOID_ATONORMATIVO) ) = '8' THEN '2' -- ALTERACAO
	END,
	convert(char(10), ATO.ATODT_LEIVIGENCIAINI1,103) AS "data vigencia ato antigo sigeo",
	isnull(ATO.ATODT_ATUALIZACAO,0) as DATA,
	[ID_TIPO_ESTRUTURA] =
	CASE
	WHEN ENT.ENTFL_ORGUND = 'orgao' THEN '1'
	WHEN ENT.ENTFL_ORGUND = 'unidade' THEN '2'
	END,

	ORGAO.ENTID_ENTIDADEADM as ID_ORGAO_UNIDADE,

	ATOID_ATONORMATIVO as "ID ATO antigo sigeo"
	

FROM  ENT_ENTIDADEADMINISTRATIVA ENT, ENT_ENTIDADEADMINISTRATIVA ORGAO, ATO_ATONORMATIVO ATO, TAL_TIPOALTERACAO TAL
WHERE ENT.ENTID_ENTIDADEADM = ATO.ENTID_ENTIDADEADM
	AND    SUBSTRING(ENT.ENTCD_ENTIDADEADM, 1,3) = SUBSTRING(ORGAO.ENTCD_ENTIDADEADM, 1,3)
	AND   ATO.TALID_TIPOALTERACAO = TAL.TALID_TIPOALTERACAO
	and   ORGAO.ENTFL_ORGUND='orgao'
	and   ORGAO.ENTFL_ATIVO = 'ativo'
	--AND   ENT.ENTID_ENTIDADEADM = 819 -- ID DO  ÓRGÃO OU UNIDADE

group by ORGAO.ENTID_ENTIDADEADM,ENT.ENTID_ENTIDADEADM,ATO.ENTNM_SIGLA,ATO.ENTNM_ENTIDADEADM,TALNM_TIPOALTERACAO,ATODT_LEIVIGENCIAINI1,ATODT_ATUALIZACAO,ENT.ENTFL_ORGUND,ATOID_ATONORMATIVO	

ORDER BY ATO.[ATOID_ATONORMATIVO]





/* consulta antiga*/

SELECT  
	ENT.ENTID_ENTIDADEADM,
	ATO.ENTNM_SIGLA,
	ATO.ENTNM_ENTIDADEADM,
	TALNM_TIPOALTERACAO,
	ATO.ATONM_LEITIPOINICIAL + ' - ' +  CONVERT(CHAR(10),ATO.ATONU_LEINUMEROINICIAL) AS LEI_NUMERO,
	convert(char(10), ATO.ATODT_LEIVIGENCIAINI1,103) AS DTINI1,
	ATO.*

FROM  ENT_ENTIDADEADMINISTRATIVA ENT, ATO_ATONORMATIVO ATO, TAL_TIPOALTERACAO TAL
WHERE ENT.ENTID_ENTIDADEADM = ATO.ENTID_ENTIDADEADM
	AND   ENT.ENTID_ENTIDADEADM = 1128
	AND   ATO.TALID_TIPOALTERACAO = TAL.TALID_TIPOALTERACAO

ORDER BY ATO.[ATOID_ATONORMATIVO]

/* /////////////////////////// ENT_ENTIDADEADMINISTRATIVA ///////////////////////// */

SELECT [ENTID_ENTIDADEADM]
      ,[ENTCD_ENTIDADEADM]
      ,[ENTFL_ATIVO]
      ,[ENTFL_ORGUND]
      ,[ENTNU_CNPJ]
      ,[ENTNM_ENTIDADEADM]
      ,[ENTNM_SIGLA]
      ,[ENTNM_LOGRADOURO]
      ,[ENTCD_CEP]
      ,[ENTNM_COMPLEMENTO]
      ,[ENTNM_BAIRRO]
      ,[ENTNM_SITE]
      ,[ENTNM_EMAIL]
      ,[FUNID_FUNCAO]
      ,[ENTFL_INFORMAL]
      ,[USUID_USUARIO]
      ,[ENTDT_ATUALIZACAO]
      ,[PODID_TIPOPODER]
      ,[ADMID_TIPOADM]
      ,[ENTNM_DIRIGENTE]
      ,[ENTNU_TELEFONE]
      ,[ENTDS_DESCRICAO]
      ,[ENTNM_EMAILDIRIG]
  FROM [SIGEO].[dbo].[ENT_ENTIDADEADMINISTRATIVA]

  WHERE [ENTID_ENTIDADEADM] = 1885

  WHERE [ENTFL_ATIVO] = 'ativo'


/* /////////////////////////// RELAÇÃO DE ORGAO E UNIDADES DESSE ÓRGÃO ////////////////////////// */

EQUIPARADO COM ESTRUTURA_ORGANIZACIONAL (NOVO_SIGEO)


/* consulta nova para migracao excell */

declare @ORGAO int;
declare @ENTID_SUBORDINACAO int;
set @ORGAO = 1332;
SELECT

	ENT2.ENTID_ENTIDADEADM as ID, 
	ENT2.ENTNM_SIGLA as SIGLA,
	ENT2.ENTNM_ENTIDADEADM as DESCRICAO,
	'' as ID_ATO_NORMATIVO ,
	'1' as ID_SIT_ESTR_ORGANIZACIONAL,
	'' as ID_ENDERECO,
	'' as DESC_TIPO_HIERARQUIA, 
	'' as ID_TIPO_HIERARQUIA,
	'' as DESC_FUNCAO,
	'' as ID_FUNCAO,
	'' as COMPETENCIA, 
	'' as FINALIDADE, 
	'' as EMAIL, 
	'' as TELEFONE, 

	[ID_TIPO_ESTRUTURA] =
	CASE
	WHEN ENT2.ENTFL_ORGUND = 'orgao' THEN '1'
	WHEN ENT2.ENTFL_ORGUND = 'unidade' THEN '2'
	END,

	[ID_TIPO_ACAO_ATO_NORMATIVO] =
	CASE
	WHEN (SELECT TALID_TIPOALTERACAO FROM ATO_ATONORMATIVO WHERE ATOID_ATONORMATIVO =  MAX(ATO.ATOID_ATONORMATIVO) ) = '1' THEN '1' -- CRIACAO
	WHEN (SELECT TALID_TIPOALTERACAO FROM ATO_ATONORMATIVO WHERE ATOID_ATONORMATIVO =  MAX(ATO.ATOID_ATONORMATIVO) ) = '2' THEN '7' -- EXTINCAO
	WHEN (SELECT TALID_TIPOALTERACAO FROM ATO_ATONORMATIVO WHERE ATOID_ATONORMATIVO =  MAX(ATO.ATOID_ATONORMATIVO) ) = '3' THEN '2' -- ALTERACAO
	WHEN (SELECT TALID_TIPOALTERACAO FROM ATO_ATONORMATIVO WHERE ATOID_ATONORMATIVO =  MAX(ATO.ATOID_ATONORMATIVO) ) = '4' THEN '2' -- ALTERACAO
	WHEN (SELECT TALID_TIPOALTERACAO FROM ATO_ATONORMATIVO WHERE ATOID_ATONORMATIVO =  MAX(ATO.ATOID_ATONORMATIVO) ) = '6' THEN '7' -- EXTINCAO
	WHEN (SELECT TALID_TIPOALTERACAO FROM ATO_ATONORMATIVO WHERE ATOID_ATONORMATIVO =  MAX(ATO.ATOID_ATONORMATIVO) ) = '7' THEN '5' -- TRANSFORMACAO
	WHEN (SELECT TALID_TIPOALTERACAO FROM ATO_ATONORMATIVO WHERE ATOID_ATONORMATIVO =  MAX(ATO.ATOID_ATONORMATIVO) ) = '8' THEN '2' -- ALTERACAO
	END,
	
	'' as "OBS_ATO_NORMATIVO",

	ENT2.ENTNU_CNPJ as CNPJ, 
	'' as SITE,	
	'' as HORARIO_FUNCIONAMENTO, 
	'' as ID_UNIDADE_REPRESENTACAO, 	
	'' as "ID_ORGAO_ORGAOCOLEGIADO", 

	[ID_ORGAO_UNIDADE] =
	CASE
	WHEN ENT2.ENTFL_ORGUND = 'unidade' THEN (ENT.ENTID_ENTIDADEADM) 
	END,
		
	[ID_ORGAO_VINCULACAO] =
	CASE
	WHEN ENT2.ENTFL_ORGUND = 'orgao' THEN (SELECT TOP 1 ENTID_VINCULADA  FROM [SIGEO].[dbo].[VIN_HISVINCULACAO]  WHERE [ENTID_ENTIDADEADM] = @ORGAO  order by [ATOID_ATONORMATIVO] desc)
	END,

	[ID_UNIDADE_SUBORDINACAO] = 
	CASE 
	WHEN	
		(
			CASE
			WHEN ENT2.ENTFL_ORGUND = 'unidade' THEN (SELECT top 1 [ENTID_SUBORDINACAO] FROM [SIGEO].[dbo].[SUB_HISSUBORDINACAO] where [ENTID_ENTIDADEADM] = ENT2.ENTID_ENTIDADEADM order by [ATOID_ATONORMATIVO] desc)
			END
		) = @ORGAO 
	THEN null
	ELSE ( SELECT top 1 [ENTID_SUBORDINACAO] FROM [SIGEO].[dbo].[SUB_HISSUBORDINACAO] where [ENTID_ENTIDADEADM] = ENT2.ENTID_ENTIDADEADM order by [ATOID_ATONORMATIVO] desc)
	END,

	'' as DATA_FIM
		
	--MAX(ATOID_ATONORMATIVO) AS ATOID

FROM   ENT_ENTIDADEADMINISTRATIVA ENT, ENT_ENTIDADEADMINISTRATIVA ENT2,ATO_ATONORMATIVO ATO
WHERE  ENT.ENTID_ENTIDADEADM = @ORGAO
AND    SUBSTRING(ENT2.ENTCD_ENTIDADEADM, 1,3) = SUBSTRING(ENT.ENTCD_ENTIDADEADM, 1,3)
AND    ENT2.ENTFL_ATIVO = 'ATIVO'      
AND    ENT2.ENTID_ENTIDADEADM = ATO.ENTID_ENTIDADEADM   
GROUP BY ENT2.ENTID_ENTIDADEADM, ENT2.ENTCD_ENTIDADEADM, ENT2.ENTNM_SIGLA, ENT2.ENTNM_ENTIDADEADM,ENT2.ENTFL_ORGUND,ENT2.ENTNU_CNPJ,ENT.ENTID_ENTIDADEADM

ORDER BY ENT2.ENTCD_ENTIDADEADM








/* consulta antiga */

SELECT
	ENT2.ENTID_ENTIDADEADM as ID, 
	sigeo.DBO.coloca_ponto_codigo(ENT2.ENTCD_ENTIDADEADM) as CODIGO, 
	ENT2.ENTNM_SIGLA, 
	ENT2.ENTNM_ENTIDADEADM, 
	MAX(ATO.ATOID_ATONORMATIVO) AS ATOID,
	(SELECT TALID_TIPOALTERACAO FROM ATO_ATONORMATIVO WHERE ATOID_ATONORMATIVO =  MAX(ATO.ATOID_ATONORMATIVO) ) as TALID_TIPOALTERACAO

FROM   ENT_ENTIDADEADMINISTRATIVA ENT, ENT_ENTIDADEADMINISTRATIVA ENT2,ATO_ATONORMATIVO ATO
WHERE  ENT.ENTID_ENTIDADEADM = 1127
AND    SUBSTRING(ENT2.ENTCD_ENTIDADEADM, 1,3) = SUBSTRING(ENT.ENTCD_ENTIDADEADM, 1,3)
AND    ENT2.ENTFL_ATIVO = 'ATIVO'      
AND    ENT2.ENTID_ENTIDADEADM = ATO.ENTID_ENTIDADEADM   
GROUP BY ENT2.ENTID_ENTIDADEADM, ENT2.ENTCD_ENTIDADEADM, ENT2.ENTNM_SIGLA, ENT2.ENTNM_ENTIDADEADM

ORDER BY ENT2.ENTCD_ENTIDADEADM 


/*/////////////////////////////// PEGA SUBORDINAÇÃO DA UNIDADE ///////////////////////////// */

SELECT [SUBID_SUBORDINACAO]
	,[ENTID_ENTIDADEADM]
	,[ENTID_SUBORDINACAO]
	,[ATOID_ATONORMATIVO]
	,[SUBFL_ATIVO]
FROM [SIGEO].[dbo].[SUB_HISSUBORDINACAO]

where [ENTID_ENTIDADEADM] = 1885

order by [ATOID_ATONORMATIVO] desc


/*/////////////////////////////// PEGA VINCULACAO DO ORGAO ///////////////////////////// */

SELECT TOP 1 [VINID_HISVINCULADO]
      ,[ENTID_ENTIDADEADM]
      ,[ENTID_VINCULADA]
      ,[ATOID_ATONORMATIVO]
      ,[VINFL_ATIVO]
  FROM [SIGEO].[dbo].[VIN_HISVINCULACAO]

  WHERE [ENTID_ENTIDADEADM] = 55

  order by [ATOID_ATONORMATIVO] desc

  /* ////////////////////  LISTA DO ATOS ÚNICOS SEM REPETIÇÃO PARA MIGRAÇÃO NOVO SIGEO //////////////////////// */

  SELECT
	
	ATOID_ATONORMATIVO as ID,

	[ID_TIPO_ATO_NORMATIVO] =
	CASE
	WHEN ATONM_LEITIPOINICIAL = 'LEI' THEN '1'
	WHEN ATONM_LEITIPOINICIAL = 'DECRETO' THEN '2'
	WHEN ATONM_LEITIPOINICIAL = 'PORTARIA' THEN '3'
	WHEN ATONM_LEITIPOINICIAL = 'ATA' THEN '4'
	END,

	ATONM_LEITIPOINICIAL AS TIPO,
	ATONU_LEINUMEROINICIAL AS NUMERO,
	ATODT_LEIVIGENCIAINI1 AS DATA,
	'' AS DATA_PUBLICACAO,
	'' AS CAMINHO_DOCUMENTO,	
	'' AS OBSERVACAO,
	 1 AS ID_SITUACAO,
	 '' AS CAPUT,
	 '' AS INTRODUCAO,	 
	 '' AS CONTEUDO,
	 '' AS FL_TEM_DOC

FROM ATO_ATONORMATIVO ATO1

WHERE 

	ATONM_LEITIPOINICIAL is not null and
	ATONU_LEINUMEROINICIAL is not null and
	ATONM_LEITIPOINICIAL <> '' and
	ATONU_LEINUMEROINICIAL <> '' and

	ATO1.ATOID_ATONORMATIVO in
	(
		SELECT  MAX(ATO2.ATOID_ATONORMATIVO) FROM ATO_ATONORMATIVO ATO2	
		GROUP BY ATONM_LEITIPOINICIAL,ATONU_LEINUMEROINICIAL
	)

ORDER BY ATONU_LEINUMEROINICIAL


 /* ////////////////////  LISTA DO ATOS NULOS //////////////////////// */

  SELECT 
	ENTID_ENTIDADEADM,
	ATOID_ATONORMATIVO	,
	--TALID_TIPOALTERACAO	,
	--ENTCD_ENTIDADEADM	,
	--ENTNM_SIGLA	ENTNM_ENTIDADEADM	,
	ATONM_LEITIPOINICIAL	,
	ATONU_LEINUMEROINICIAL	,
	ATODT_LEIVIGENCIAINI1	,
	--ATODT_LEIVIGENCIAINI2	,
	--ATONM_LEITIPOFINAL	,
	--ATONU_LEINUMEROFINAL	,
	--ATODT_LEIVIGENCIAFIM1	,
	--ATODT_LEIVIGENCIAFIM2	,
	ATODS_OBSERVACAO	,
	ENTFL_ORGUND	,
	--USUID_USUARIO	,
	ATODT_ATUALIZACAO	
	--ENTFL_INFORMAL	,
	--PODID_TIPOPODER	ADMID_TIPOADM

  FROM [SIGEO].[dbo].[ATO_ATONORMATIVO]

  where ENTID_ENTIDADEADM = 3911

  where ATONM_LEITIPOINICIAL is null or ATONU_LEINUMEROINICIAL is null



  /*///////// ÓRGÃOS ATIVOS ////////// */

select 
	ENTID_ENTIDADEADM, 
	sigeo.DBO.coloca_ponto_codigo(ENTCD_ENTIDADEADM)  as CODIGO, 
	ENTNM_SIGLA AS SIGLA, ENTNM_ENTIDADEADM,
	ENTNU_CNPJ

from  ent_entidadeadministrativa
where entfl_orgund = 'orgao'and entfl_ativo = 'ativo'
ORDER BY ENTNM_SIGLA

