
CREATE SEQUENCE TIPO_HIERARQUIA_ORG_ID_SEQ;
alter table TIPO_ESTRUTURA_ORGANIZACIONAL modify id default TIPO_ESTRUTURA_ORG_ID_SEQ.nextval; 

CREATE SEQUENCE TIPO_HIERARQUIA_ID_SEQ;
alter table TIPO_HIERARQUIA modify id default TIPO_HIERARQUIA_ID_SEQ.nextval; 

CREATE SEQUENCE SITUACAO_ESTRUTURA_ORG_ID_SEQ;
alter table SITUACAO_ESTRUTURA_ORGANIZACIO modify id default SITUACAO_ESTRUTURA_ORG_ID_SEQ.nextval; 

CREATE SEQUENCE ATO_NORMATIVO_ID_SEQ;
alter table ATO_NORMATIVO modify id default ATO_NORMATIVO_ID_SEQ.nextval;


alter table ENDERECO modify id default ENDERECO_ID_SEQ.nextval;
